from app.node_registry.builtin import (
    bgm,
    bilibili_search,
    concat_horizontal,
    concat_timeline,
    concat_vertical,
    concat_vertical_timeline,
    export,
    material_library_ingest,
    material_search,
    replace_audio,
    source,
    speech_to_subtitle,
    subtitle,
    subtitle_to_speech,
    subtitle_translate,
    transcode,
    trim,
    url_download,
    watermark,
    x_search,
    x_upload,
    xiaohongshu_search,
    youtube_search,
    youtube_upload,
    zip_records,
)

BUILTIN_MODULES = (
    source,
    concat_horizontal,
    concat_vertical,
    concat_timeline,
    concat_vertical_timeline,
    trim,
    watermark,
    subtitle,
    speech_to_subtitle,
    subtitle_translate,
    subtitle_to_speech,
    bgm,
    replace_audio,
    transcode,
    url_download,
    material_library_ingest,
    material_search,
    youtube_search,
    x_search,
    xiaohongshu_search,
    bilibili_search,
    zip_records,
    export,
    youtube_upload,
    x_upload,
)

__all__ = [
    "BUILTIN_MODULES",
    *[module.__name__.rsplit(".", 1)[-1] for module in BUILTIN_MODULES],
]
