services:
  xtts-api:
    build: .
    container_name: xtts_v2_api
    ports:
      - "8000:8000"
    environment:
      - USE_GPU=true
      - XTTS_MODEL_NAME=tts_models/multilingual/multi-dataset/xtts_v2
      - OUTPUT_DIR=/app/output
      - COQUI_TOS_AGREED=1
      - DEFAULT_SPEAKER_WAV=/home/taiwei/VideoProcess/TextToAudio/voicesource/sample.wav
    volumes:
      - ./output:/app/output
      - ./models:/root/.local/share/tts
      - /home/taiwei/VideoProcess/TextToAudio/voicesource:/home/taiwei/VideoProcess/TextToAudio/voicesource:ro
    gpus: all
    restart: unless-stopped
    networks:
      videoprocess_net:
        aliases:
          - xtts-api
          - xtts_v2_api

networks:
  videoprocess_net:
    external: true



